import React from 'react';
import { Link } from 'react-router';
import { useLanguage } from '../contexts/LanguageContext';
import type { MetaFunction } from 'react-router';
import { Flame, Calculator, ShieldCheck, ArrowRight, CheckCircle2, Wrench, Layers, HelpCircle, Activity } from 'lucide-react';

export const meta: MetaFunction = () => {
    const title = "Walking Beam Furnace Revamping Solutions | EcoReheating";
    const description = "Engineering guide to walking beam furnace design, mechanism, and turnkey furnace revamping solutions. Cut reheat furnace fuel usage by 15-25% with zero CAPEX.";
    const image = "https://www.ecoreheating.com/hero-bg.png";

    return [
        { title },
        { name: "description", content: description },
        { property: "og:type", content: "article" },
        { property: "og:title", content: title },
        { property: "og:description", content: description },
        { property: "og:image", image },
        { property: "og:image:width", content: "1200" },
        { property: "og:image:height", content: "630" },
        { name: "twitter:card", content: "summary_large_image" },
        { name: "twitter:title", content: title },
        { name: "twitter:description", content: description },
        { name: "twitter:image", content: image },
    ];
};

const WalkingBeamGuide: React.FC = () => {
    const { language: lang } = useLanguage();

    const faqSchema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {
                "@type": "Question",
                "name": "What is a reheating furnace and its primary working principle?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "A reheating furnace of a rolling mill is an industrial thermal reactor that heats solid steel stock (billets, blooms, or slabs) to plastically deformable temperatures (typically 1,150°C to 1,250°C). Its working principle involves transferring thermal energy generated by air-gas burners to steel charges via radiation and forced convection while maintaining tight furnace temperature control."
                }
            },
            {
                "@type": "Question",
                "name": "What are the different types of reheating furnace used in steel mills?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "The primary types of reheating furnace in steel rolling mills include pusher-type furnaces, walking beam type reheating furnaces, walking hearth furnaces, and rotary hearth furnaces. Among these, the walking beam furnace is the premier choice for modern rolling mill efficiency and slab surface quality."
                }
            },
            {
                "@type": "Question",
                "name": "How does the walking beam furnace mechanism eliminate skid marks?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "The walking beam furnace mechanism uses stationary and moving refractory-insulated beams operated by eccentric or hydraulic lift-and-shift drives. Because the moving beams periodically lift stock off the stationary hearth rather than sliding it across water-cooled rails, physical contact with cold skid pipes is eliminated, removing thermal shadow skid marks."
                }
            },
            {
                "@type": "Question",
                "name": "Can an existing pusher furnace be revamped into a walking beam furnace?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Yes. Pusher-to-walking-beam revamping is a proven engineering solution. By retaining the existing civil foundation and outer shell while retrofitting the mechanical walking beam mechanism, modern combustion staging, and fiber roofs, mills achieve 12-20% fuel savings within a standard 15-25 day maintenance window."
                }
            },
            {
                "@type": "Question",
                "name": "What are furnace revamping solutions under the zero CAPEX model?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Furnace revamping solutions under the zero CAPEX model allow steel mills to execute turnkey walking beam upgrades with $0 upfront investment. The engineering provider finances all hardware, materials, and labor, recovering capital solely through a verified share of monthly fuel and scale savings."
                }
            }
        ]
    };

    // Translations
    const t = {
        en: {
            title: "Walking Beam Reheating Furnace: Design, Mechanism & Revamping Guide",
            subtitle: "Engineering breakdown of reheat furnace temperature control, walking beam mechanism design, and turnkey furnace revamping solutions under the Zero CAPEX model.",
            introTitle: "1. What is a Reheating Furnace? Working Principle & Types",
            introText: "A reheating furnace of rolling mill operations is the thermal core of any modern steel rolling mill. The fundamental reheating furnace working principle is to uniformly heat solid steel stock—billets, blooms, and slabs—from ambient temperature up to 1,150°C–1,250°C for plastic deformation in the rolling stands. Among the classic types of reheating furnace (including pusher, walking hearth furnace, and rotary hearth systems), the walking beam type reheating furnace is globally recognized as the gold standard for high-throughput rolling mill engineering.",
            mechanismTitle: "2. Walking Beam Furnace Mechanism & Design Architecture",
            mechanismText: "The walking beam furnace mechanism separates stock transportation from mechanical sliding. As illustrated in any modern walking beam furnace diagram, hydraulic cylinder linkages or eccentric cam drives periodically rise through slots in the stationary hearth, lift the steel charges, travel forward, and lower them back onto stationary supports. This walking beam furnace design allows 360-degree radiant heat penetration across both top and bottom surfaces, ensuring high thermal uniformity and tight reheat furnace temperature control without surface scratching.",
            comparisonTitle: "3. Pusher vs. Walking Beam vs. Walking Hearth Furnace",
            comparisonText: "In a legacy pusher reheat furnace of a steel mill, billets are pushed against each other across water-cooled skid rails, causing deep localized cold zones known as 'skid marks' that necessitate burning excess fuel to compensate. In contrast, walking beam steel mill installations eliminate sliding friction, reduce skid heat loss by 10-15%, and outperform the walking hearth furnace when handling large, varied cross-section slabs.",
            liningTitle: "4. Heat Loss Mitigation: Full-Fiber Roof & Low Thermal Inertia",
            liningText: "Traditional refractory brick or castable furnace crowns store massive amounts of thermal energy. Retrofitting with a modular CISA T80-certified all-ceramic fiber roof reduces ceiling heat flux by over 40% and cuts furnace weight by 90%. This enables rapid cold startups in under 2 hours compared to 24–48 hours for legacy refractory linings, saving substantial fuel during rolling mill shutdowns.",
            revampTitle: "5. Turnkey Furnace Revamping Solutions: Pusher to Walking Beam",
            revampText: "Unlike traditional walking beam furnace manufacturers that demand capital expenditures exceeding $2M-$5M and prolonged plant shutdowns, our turnkey furnace revamping solutions enable steel mills in India, the USA, and Southeast Asia to modernize existing pusher furnaces into high-efficiency walking beam systems in just 15-25 days during planned maintenance. When combined with our furnace revamping solutions zero capex model, mills pay $0 upfront and fund the upgrade entirely from verified 12-20% fuel savings.",
            calculatorCta: "Heat Balance Calculator",
            rfqCta: "Request Turnkey Revamp Study",
            back: "← Back to Home",
        },
        vi: {
            title: "Lò Nung Dầm Bước: Thiết Kế, Cơ Cấu & Cải Tạo Nâng Cấp 2026",
            subtitle: "Phân tích kỹ thuật cơ cấu dầm bước, kiểm soát nhiệt độ lò nung và giải pháp cải tạo lò nung trọn gói theo mô hình Zero CAPEX cho nhà máy thép.",
            introTitle: "1. Lò Nung Lại Là Gì? Nguyên Lý Hoạt Động & Phân Loại",
            introText: "Lò nung lại (reheating furnace) là trái tim nhiệt luyện của mọi nhà máy cán thép. Nguyên lý hoạt động là gia nhiệt đồng đều phôi thép từ nhiệt độ môi trường lên 1.150°C–1.250°C để cán nóng. Trong các loại lò nung (lò đẩy, lò đáy sàn walking hearth, lò dầm bước), lò nung dầm bước (walking beam type reheating furnace) là tiêu chuẩn vàng về chất lượng phôi và tiết kiệm năng lượng.",
            mechanismTitle: "2. Cơ Cấu & Bản Vẽ Thiết Kế Lò Nung Dầm Bước",
            mechanismText: "Cơ cấu lò dầm bước vận hành bằng hệ thống thủy lực hoặc cam lệch tâm, định kỳ nâng phôi lên khỏi sàn tĩnh, bước về phía trước và hạ xuống sàn cố định. Thiết kế này cho phép nhiệt bức xạ bao quanh 4 mặt phôi, mang lại sự đồng đều nhiệt tuyệt đối và kiểm soát nhiệt độ dải hẹp mà không làm xước bề mặt phôi thép.",
            comparisonTitle: "3. So Sánh Lò Đẩy, Lò Dầm Bước và Lò Đáy Sàn",
            comparisonText: "Trong các lò nung đẩy truyền thống, phôi bị trượt trên đường ray làm mát bằng nước gây ra hiện tượng vết đen (skid marks) làm hao phí 10-15% nhiệt lượng. Lò dầm bước loại bỏ hoàn toàn ma sát trượt và vượt trội hơn lò đáy sàn khi gia nhiệt các loại phôi đa dạng.",
            liningTitle: "4. Giảm Tổn Thất Nhiệt: Mái Lò Toàn Sợi Gốm Chuẩn T80",
            liningText: "Mái lò gạch chịu lửa truyền thống có quán tính nhiệt cực lớn. Chuyển sang mái toàn sợi gốm đạt chuẩn CISA T80 giúp giảm hơn 40% tổn thất nhiệt qua nóc lò, giảm 90% trọng lượng mái và cho phép khởi động lò nhanh dưới 2 giờ.",
            revampTitle: "5. Giải Pháp Cải Tạo Lò Nung Trọn Gói: Chuyển Đổi Sang Dầm Bước",
            revampText: "Giải pháp cải tạo lò nung trọn gói (furnace revamping solutions) của chúng tôi giúp chuyển đổi lò đẩy sang dầm bước trong 15-25 ngày bảo dưỡng. Theo mô hình Zero CAPEX, nhà máy đầu tư 0đ và trả chi phí từ khoản tiết kiệm 12-20% nhiên liệu thực tế.",
            calculatorCta: "Công Cụ Cân Bằng Nhiệt",
            rfqCta: "Yêu Cầu Khảo Sát Cải Tạo",
            back: "← Quay lại Trang chủ",
        },
        id: {
            title: "Tungku Reheating Walking Beam: Desain, Mekanisme & Solusi Retrofit",
            subtitle: "Analisis teknis mekanisme tungku walking beam, kontrol suhu reheat furnace, dan solusi retrofit tungku turnkey dengan model Zero CAPEX.",
            introTitle: "1. Apa itu Reheating Furnace? Prinsip Kerja & Tipe",
            introText: "Reheating furnace adalah inti termal dari pabrik rolling baja. Prinsip kerjanya adalah memanaskan billet baja secara merata hingga 1.150°C-1.250°C. Di antara tipe tungku pemanas (pusher, walking hearth, walking beam), walking beam type reheating furnace adalah standar emas efisiensi modern.",
            mechanismTitle: "2. Mekanisme & Desain Tungku Walking Beam",
            mechanismText: "Mekanisme walking beam menggunakan sistem hidrolik untuk mengangkat, melangkah maju, dan menurunkan billet. Desain ini memungkinkan perpindahan panas radiasi 360 derajat di seluruh permukaan atas dan bawah tanpa menggores baja.",
            comparisonTitle: "3. Tungku Pusher vs. Walking Beam vs. Walking Hearth",
            comparisonText: "Tungku pusher konvensional menyebabkan titik dingin (skid marks) akibat pipa pendingin air. Tungku walking beam mengeliminasi gesekan dan menghemat 10-15% energi dibandingkan teknologi lama.",
            liningTitle: "4. Mitigasi Kehilangan Panas: Atap Serat Keramik Modular",
            liningText: "Mengganti atap bata tahan api dengan atap serat keramik modular T80 mengurangi kehilangan panas hingga 40% dan memungkinkan startup cepat dalam waktu kurang dari 2 jam.",
            revampTitle: "5. Solusi Retrofit Tungku Turnkey: Pusher ke Walking Beam",
            revampText: "Solusi revamping tungku turnkey kami memungkinkan modernisasi tungku pusher yang ada dalam waktu 15-25 hari shutdown terencana. Melalui model zero CAPEX, pabrik berinvestasi $0 di awal dan membayar dari penghematan bahan bakar 12-20%.",
            calculatorCta: "Kalkulator Keseimbangan Panas",
            rfqCta: "Minta Studi Kelayakan",
            back: "← Kembali ke Beranda",
        },
        "pt-br": {
            title: "Forno de Vigas Caminhantes: Projeto, Mecanismo e Soluções de Reforma",
            subtitle: "Detalhamento de engenharia para controle de temperatura de forno de reaquecimento, mecanismo walking beam e soluções de reforma sob o modelo Zero CAPEX.",
            introTitle: "1. O que é um Forno de Reaquecimento? Princípio e Tipos",
            introText: "O forno de reaquecimento (reheating furnace) é o coração térmico da laminação de aço. Seu princípio de funcionamento é aquecer tarugos de aço até 1.150°C-1.250°C. Dentre os tipos de fornos industriais (empurrador, walking hearth, walking beam), o forno do tipo walking beam é o padrão global de eficiência.",
            mechanismTitle: "2. Mecanismo e Projeto do Forno Walking Beam",
            mechanismText: "O mecanismo walking beam utiliza atuadores hidráulicos para elevar, avançar e pousar os tarugos de aço. Esse projeto permite aquecimento radiante uniforme em quatro faces e controle preciso de temperatura.",
            comparisonTitle: "3. Forno Empurrador vs. Walking Beam vs. Walking Hearth",
            comparisonText: "Fornos empurradores geram marcas de skid mark e perdas térmicas na refrigeração. Fornos walking beam eliminam o atrito por deslizamento e reduzem o consumo térmico em 10-15%.",
            liningTitle: "4. Redução de Perdas Térmicas: Teto Modular de Fibra Cerâmica",
            liningText: "A substituição de tetos refratários pesados por módulos de fibra cerâmica T80 reduz perdas térmicas em mais de 40% e permite partidas rápidas em menos de 2 horas.",
            revampTitle: "5. Soluções Turnkey de Reforma de Forno: Conversão para Walking Beam",
            revampText: "Nossas soluções de reforma de forno (furnace revamping solutions) permitem converter fornos empurradores existentes em vigas caminhantes em 15-25 dias. Sob o modelo zero CAPEX, sua usina investe $0 e paga através da economia de 12-20% em combustível.",
            calculatorCta: "Calculadora de Balanço Térmico",
            rfqCta: "Solicitar Estudo de Viabilidade",
            back: "← Voltar para a Home",
        }
    };

    const currentT = t[lang as keyof typeof t] || t.en;

    const heatBalanceLink = lang === 'en'
        ? '/calculators/reheating-furnace-heat-balance'
        : `/${lang}/calculators/reheating-furnace-heat-balance`;

    const assessmentLink = lang === 'en'
        ? '/about#assessment'
        : `/${lang}/about#assessment`;

    return (
        <div className="bg-slate-950 min-h-screen text-slate-100 py-20 px-4 sm:px-6 lg:px-8 relative overflow-hidden">
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
            />
            
            <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,rgba(249,115,22,0.1),transparent_70%)] pointer-events-none" />
            <div className="absolute inset-0 carbon-pattern pointer-events-none" />

            <div className="max-w-4xl mx-auto relative z-10">
                <div className="mb-8">
                    <Link to={lang === 'en' ? '/' : `/${lang}`} className="text-furnace-500 hover:text-furnace-600 transition-colors font-medium">
                        {currentT.back}
                    </Link>
                </div>

                {/* Hero Header */}
                <div className="border-b border-slate-800 pb-8 mb-12">
                    <span className="px-3 py-1 text-xs font-semibold tracking-wider text-furnace-500 uppercase bg-furnace-500/10 border border-furnace-500/20 rounded-full flex items-center gap-1.5 w-fit">
                        <ShieldCheck size={12} />
                        Engineering Pillar & Solutions
                    </span>
                    <h1 className="mt-4 text-3xl sm:text-4xl lg:text-5xl font-extrabold text-white font-heading tracking-tight leading-tight">
                        {currentT.title}
                    </h1>
                    <p className="mt-4 text-lg text-slate-400 leading-relaxed font-sans">
                        {currentT.subtitle}
                    </p>
                </div>

                {/* Article Content */}
                <div className="space-y-10 text-slate-300 leading-relaxed text-base font-sans">
                    {/* Section 1 - What is reheating furnace */}
                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white flex items-center gap-2 font-heading">
                            <Flame className="text-furnace-500" size={22} />
                            {currentT.introTitle}
                        </h2>
                        <p>{currentT.introText}</p>
                    </section>

                    {/* Section 2 - Mechanism & Design */}
                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white flex items-center gap-2 font-heading">
                            <Layers className="text-furnace-500" size={22} />
                            {currentT.mechanismTitle}
                        </h2>
                        <p>{currentT.mechanismText}</p>
                    </section>

                    {/* Section 3 - Comparison */}
                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white flex items-center gap-2 font-heading">
                            <Activity className="text-furnace-500" size={22} />
                            {currentT.comparisonTitle}
                        </h2>
                        <p>{currentT.comparisonText}</p>
                    </section>

                    {/* Section 4 - Fiber Roof */}
                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white flex items-center gap-2 font-heading">
                            <Flame className="text-furnace-500" size={22} />
                            {currentT.liningTitle}
                        </h2>
                        <p>{currentT.liningText}</p>
                    </section>

                    {/* Section 5 - Revamping */}
                    <section className="space-y-4 bg-slate-900/60 border border-slate-800 p-6 rounded-2xl">
                        <h2 className="text-2xl font-bold text-white flex items-center gap-2 font-heading">
                            <Wrench className="text-furnace-500" size={22} />
                            {currentT.revampTitle}
                        </h2>
                        <p>{currentT.revampText}</p>
                        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-2">
                            <div className="bg-slate-950/80 p-3 rounded-lg border border-slate-800">
                                <div className="text-furnace-400 font-bold text-lg">12-20%</div>
                                <div className="text-xs text-slate-400">Typical Fuel Gas Reduction</div>
                            </div>
                            <div className="bg-slate-950/80 p-3 rounded-lg border border-slate-800">
                                <div className="text-furnace-400 font-bold text-lg">&lt; 25 Days</div>
                                <div className="text-xs text-slate-400">Installation Shutdown Cycle</div>
                            </div>
                            <div className="bg-slate-950/80 p-3 rounded-lg border border-slate-800">
                                <div className="text-furnace-400 font-bold text-lg">$0 CAPEX</div>
                                <div className="text-xs text-slate-400">Energy Steward Model Option</div>
                            </div>
                        </div>
                    </section>

                    {/* Dual High-Conversion Action Box */}
                    <div className="glass-panel border-furnace-500/30 rounded-2xl p-6 sm:p-8 bg-gradient-to-r from-slate-900 via-slate-900 to-slate-950 my-12 space-y-6">
                        <div>
                            <span className="text-xs uppercase font-bold tracking-wider text-furnace-400 block mb-1">
                                Engineering Tools & Commercial Proposal
                            </span>
                            <h3 className="text-xl font-bold text-white">Optimize Your Mill's Walking Beam Performance</h3>
                            <p className="text-sm text-slate-400 mt-1">
                                Whether auditing specific fuel consumption (SFC) or planning a full pusher-to-walking-beam revamping, our engineering team provides direct thermodynamic verification.
                            </p>
                        </div>
                        <div className="flex flex-col sm:flex-row gap-4">
                            <Link
                                to={heatBalanceLink}
                                className="inline-flex items-center justify-center gap-2 py-3 px-5 bg-slate-800 hover:bg-slate-700 text-white rounded-lg transition-colors font-semibold text-sm border border-slate-700"
                            >
                                <Calculator size={16} className="text-furnace-400" />
                                {currentT.calculatorCta}
                            </Link>
                            <Link
                                to={assessmentLink}
                                className="inline-flex items-center justify-center gap-2 py-3 px-6 bg-furnace-500 hover:bg-furnace-600 text-white rounded-lg transition-colors font-bold text-sm uppercase tracking-wider shadow-lg shadow-furnace-500/20"
                            >
                                {currentT.rfqCta}
                                <ArrowRight size={16} />
                            </Link>
                        </div>
                    </div>

                    {/* FAQ Schema display */}
                    <section className="border-t border-slate-800 pt-10">
                        <h3 className="text-xl font-bold text-white mb-6 flex items-center gap-2">
                            <HelpCircle className="text-furnace-500" size={20} />
                            Frequently Asked Engineering Questions
                        </h3>
                        <div className="space-y-6">
                            <div className="bg-slate-900/50 p-5 rounded-xl border border-slate-800/80">
                                <h4 className="font-semibold text-white mb-2">Q: What is a reheating furnace and its primary working principle?</h4>
                                <p className="text-sm text-slate-400">A: A reheating furnace of a rolling mill is an industrial thermal reactor that heats solid steel stock (billets, blooms, or slabs) to plastically deformable temperatures (typically 1,150°C to 1,250°C). Its working principle involves transferring thermal energy generated by air-gas burners to steel charges via radiation and forced convection while maintaining tight reheat furnace temperature control.</p>
                            </div>
                            <div className="bg-slate-900/50 p-5 rounded-xl border border-slate-800/80">
                                <h4 className="font-semibold text-white mb-2">Q: What are the different types of reheating furnace used in steel mills?</h4>
                                <p className="text-sm text-slate-400">A: The primary types of reheating furnace in steel rolling mills include pusher-type furnaces, walking beam type reheating furnaces, walking hearth furnaces, and rotary hearth furnaces. Among these, the walking beam furnace is the premier choice for modern rolling mill efficiency and slab surface quality.</p>
                            </div>
                            <div className="bg-slate-900/50 p-5 rounded-xl border border-slate-800/80">
                                <h4 className="font-semibold text-white mb-2">Q: How does the walking beam furnace mechanism eliminate skid marks?</h4>
                                <p className="text-sm text-slate-400">A: The walking beam furnace mechanism uses stationary and moving refractory-insulated beams operated by eccentric or hydraulic lift-and-shift drives. Because the moving beams periodically lift stock off the stationary hearth rather than sliding it across water-cooled rails, physical contact with cold skid pipes is eliminated, removing thermal shadow skid marks.</p>
                            </div>
                            <div className="bg-slate-900/50 p-5 rounded-xl border border-slate-800/80">
                                <h4 className="font-semibold text-white mb-2">Q: Can an existing pusher furnace be revamped into a walking beam furnace?</h4>
                                <p className="text-sm text-slate-400">A: Yes. Pusher-to-walking-beam revamping is a proven engineering solution. By retaining the existing civil foundation and outer shell while retrofitting the mechanical walking beam mechanism, modern combustion staging, and fiber roofs, mills achieve 12-20% fuel savings within a standard 15-25 day maintenance window.</p>
                            </div>
                            <div className="bg-slate-900/50 p-5 rounded-xl border border-slate-800/80">
                                <h4 className="font-semibold text-white mb-2">Q: What are furnace revamping solutions under the zero CAPEX model?</h4>
                                <p className="text-sm text-slate-400">A: Furnace revamping solutions under the zero CAPEX model allow steel mills to execute turnkey walking beam upgrades with $0 upfront investment. The engineering provider finances all hardware, materials, and labor, recovering capital solely through a verified share of monthly fuel and scale savings.</p>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    );
};

export default WalkingBeamGuide;
