import React from 'react';
import { Link } from 'react-router';
import { useLanguage } from '../contexts/LanguageContext';
import type { MetaFunction } from 'react-router';
import { Flame, Calculator, ShieldCheck, ArrowRight, CheckCircle2, Wrench, Layers, HelpCircle, Activity, BarChart3, Settings, ShieldAlert, BookOpen } from 'lucide-react';

export const meta: MetaFunction = () => {
    const title = "Walking Beam Furnace Revamping & Retrofit | EcoReheating";
    const description = "Engineering guide to walking beam furnace design, mechanism, and turnkey furnace revamping solutions. Cut reheat furnace fuel usage by 15-25% with zero CAPEX.";
    const image = "https://www.ecoreheating.com/hero-bg.png";
    const pageUrl = "https://www.ecoreheating.com/furnaces/walking-beam-reheating-furnace";

    return [
        { title },
        { name: "description", content: description },
        { property: "og:type", content: "article" },
        { property: "og:url", content: pageUrl },
        { property: "og:site_name", content: "EcoReheating" },
        { property: "og:title", content: title },
        { property: "og:description", content: description },
        { property: "og:image", content: image },
        { property: "og:image:width", content: "1200" },
        { property: "og:image:height", content: "630" },
        { name: "twitter:card", content: "summary_large_image" },
        { name: "twitter:title", content: title },
        { name: "twitter:description", content: description },
        { name: "twitter:image", content: image },
    ];
};

const WalkingBeamGuide: React.FC = () => {
    const { language: lang } = useLanguage();

    const faqSchema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {
                "@type": "Question",
                "name": "What is a reheating furnace and its primary working principle?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "A reheating furnace of a rolling mill is an industrial thermal reactor that heats solid steel stock (billets, blooms, or slabs) to plastically deformable temperatures (typically 1,150°C to 1,250°C). Its working principle involves transferring thermal energy generated by air-gas burners to steel charges via radiation and forced convection while maintaining tight reheat furnace temperature control."
                }
            },
            {
                "@type": "Question",
                "name": "What are the primary types of reheating furnace in steel mills?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "The primary types of reheating furnace in steel rolling mills include pusher-type furnaces, walking beam type reheating furnaces, walking hearth furnaces, and rotary hearth furnaces. Among these, the walking beam furnace is the premier choice for modern rolling mill efficiency and slab surface quality."
                }
            },
            {
                "@type": "Question",
                "name": "How does the walking beam furnace mechanism eliminate skid marks?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "The walking beam furnace mechanism uses stationary and moving refractory-insulated beams operated by eccentric or hydraulic lift-and-shift drives. Because the moving beams periodically lift stock off the stationary hearth rather than sliding it across water-cooled rails, physical contact with cold skid pipes is eliminated, removing thermal shadow skid marks."
                }
            },
            {
                "@type": "Question",
                "name": "Can an existing pusher furnace be revamped into a walking beam furnace?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Yes. Pusher-to-walking-beam revamping is a proven engineering solution. By retaining the existing civil foundation and outer shell while retrofitting the mechanical walking beam mechanism, modern combustion staging, and fiber roofs, mills achieve 12-20% fuel savings within a standard 15-25 day maintenance window."
                }
            },
            {
                "@type": "Question",
                "name": "What are furnace revamping solutions under the zero CAPEX model?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Furnace revamping solutions under the zero CAPEX model allow steel mills to execute turnkey walking beam upgrades with $0 upfront investment. The engineering provider finances all hardware, materials, and labor, recovering capital solely through a verified share of monthly fuel and scale savings."
                }
            }
        ]
    };

    return (
        <div className="bg-slate-950 min-h-screen text-slate-100 py-20 px-4 sm:px-6 lg:px-8 relative overflow-hidden">
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
            />
            
            <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,rgba(249,115,22,0.1),transparent_70%)] pointer-events-none" />
            <div className="absolute inset-0 carbon-pattern pointer-events-none" />

            <div className="max-w-4xl mx-auto relative z-10">
                <div className="mb-8">
                    <Link to={lang === 'en' ? '/' : `/${lang}`} className="text-furnace-500 hover:text-furnace-600 transition-colors font-medium">
                        {lang === 'vi' ? '← Quay lại Trang chủ' : '← Back to Home'}
                    </Link>
                </div>

                {/* Hero Header */}
                <div className="border-b border-slate-800 pb-8 mb-12">
                    <span className="px-3 py-1 text-xs font-semibold tracking-wider text-furnace-500 uppercase bg-furnace-500/10 border border-furnace-500/20 rounded-full flex items-center gap-1.5 w-fit">
                        <ShieldCheck size={12} />
                        Engineering Pillar & Solutions
                    </span>
                    <h1 className="mt-4 text-3xl sm:text-4xl lg:text-5xl font-extrabold text-white font-heading tracking-tight leading-tight">
                        Walking Beam Furnace: Design, Mechanism & Revamping Solutions
                    </h1>
                    <p className="mt-4 text-lg text-slate-400 leading-relaxed font-sans">
                        Comprehensive engineering breakdown of walking beam furnace design, hydraulic lift mechanisms, reheat furnace temperature control, and turnkey pusher-to-walking-beam revamping solutions under the Zero CAPEX model.
                    </p>
                </div>

                {/* Article Content */}
                <div className="space-y-12 text-slate-300 leading-relaxed text-base font-sans">
                    {/* Section 1 - What is reheating furnace */}
                    <section className="space-y-5">
                        <h2 className="text-2xl font-bold text-white flex items-center gap-2 font-heading">
                            <Flame className="text-furnace-500" size={22} />
                            1. What is a Reheating Furnace? Working Principle & Types
                        </h2>
                        <p>
                            A reheating furnace of rolling mill operations serves as the indispensable thermal reactor in hot metalworking. The fundamental reheating furnace working principle is to heat solid semi-finished steel stock—such as continuous cast billets, blooms, beam blanks, and heavy slabs—from ambient temperature up to plastic deformation range (typically 1,150°C to 1,250°C) prior to rolling.
                        </p>
                        <p>
                            During this thermal journey, radiant and convective heat transfer from combustion gases must heat the steel uniformly throughout its cross-section. Uneven core-to-surface temperatures cause severe dimensional tolerances, rolling stand motor overloads, and surface cracks during finishing passes.
                        </p>

                        <div className="overflow-x-auto my-6">
                            <table className="w-full text-left text-sm border border-slate-800 bg-slate-900/50 rounded-xl overflow-hidden">
                                <thead className="bg-slate-900 text-furnace-400 font-bold uppercase text-xs">
                                    <tr>
                                        <th className="p-3.5 border-b border-slate-800">Furnace Classification</th>
                                        <th className="p-3.5 border-b border-slate-800">Stock Conveyance</th>
                                        <th className="p-3.5 border-b border-slate-800">Typical Thermal Intensity</th>
                                        <th className="p-3.5 border-b border-slate-800">Primary Limitations</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-slate-800 text-slate-300">
                                    <tr>
                                        <td className="p-3.5 font-semibold text-white">Pusher-Type Furnace</td>
                                        <td className="p-3.5">Hydraulic ram slides billets on water skids</td>
                                        <td className="p-3.5">1.45 – 1.85 GJ/ton</td>
                                        <td className="p-3.5 text-red-400/90">Deep skid marks, surface scratching, pile-ups</td>
                                    </tr>
                                    <tr className="bg-furnace-950/20">
                                        <td className="p-3.5 font-semibold text-furnace-300">Walking Beam Furnace</td>
                                        <td className="p-3.5 text-slate-200">Mechanized lift-and-shift stationary/moving beams</td>
                                        <td className="p-3.5 text-emerald-400 font-bold">1.10 – 1.35 GJ/ton</td>
                                        <td className="p-3.5 text-slate-400">Higher initial mechanical complexity</td>
                                    </tr>
                                    <tr>
                                        <td className="p-3.5 font-semibold text-white">Walking Hearth Furnace</td>
                                        <td className="p-3.5">Solid refractory hearth steps forward</td>
                                        <td className="p-3.5">1.30 – 1.55 GJ/ton</td>
                                        <td className="p-3.5 text-slate-400">Limited to top-firing; slower heating rates</td>
                                    </tr>
                                    <tr>
                                        <td className="p-3.5 font-semibold text-white">Rotary Hearth Furnace</td>
                                        <td className="p-3.5">Rotating annular circular hearth</td>
                                        <td className="p-3.5">1.35 – 1.60 GJ/ton</td>
                                        <td className="p-3.5 text-slate-400">Round billets/tubes only; high floor space</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </section>

                    {/* Section 2 - Mechanism & Design */}
                    <section className="space-y-5">
                        <h2 className="text-2xl font-bold text-white flex items-center gap-2 font-heading">
                            <Layers className="text-furnace-500" size={22} />
                            2. Walking Beam Furnace Mechanism & Design Architecture
                        </h2>
                        <p>
                            The core advantage of the modern walking beam furnace mechanism lies in its complete separation of charge transportation from physical sliding friction. As visualized in any standard walking beam furnace diagram, the hearth floor consists of alternating sets of stationary refractory piers and longitudinal moving beams.
                        </p>
                        
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-6">
                            <div className="bg-slate-900/60 p-5 rounded-xl border border-slate-800">
                                <h3 className="font-bold text-white mb-2 flex items-center gap-2 text-base">
                                    <Activity size={18} className="text-furnace-400" />
                                    The 4-Stroke Kinematic Cycle
                                </h3>
                                <ul className="space-y-2 text-sm text-slate-300">
                                    <li><strong className="text-furnace-400">1. Lift Stroke:</strong> Moving beams rise vertically through hearth troughs, gently lifting stock off stationary piers.</li>
                                    <li><strong className="text-furnace-400">2. Forward Stroke:</strong> Beams advance horizontally by a preset pitch (typically 200 mm to 450 mm).</li>
                                    <li><strong className="text-furnace-400">3. Lower Stroke:</strong> Moving beams descend below the stationary hearth level, depositing billets onto support saddles.</li>
                                    <li><strong className="text-furnace-400">4. Return Stroke:</strong> Beams travel back to initial rest position beneath the hearth line.</li>
                                </ul>
                            </div>

                            <div className="bg-slate-900/60 p-5 rounded-xl border border-slate-800">
                                <h3 className="font-bold text-white mb-2 flex items-center gap-2 text-base">
                                    <Settings size={18} className="text-furnace-400" />
                                    Thermal & Sealing Engineering
                                </h3>
                                <ul className="space-y-2 text-sm text-slate-300">
                                    <li><strong className="text-furnace-400">Continuous Water Seals:</strong> Water troughs and drop-blade aprons prevent ambient cold air ingress and flue gas leakage.</li>
                                    <li><strong className="text-furnace-400">Top and Bottom Firing:</strong> Billets are elevated above the furnace floor, allowing under-hearth burners to irradiate stock undersides.</li>
                                    <li><strong className="text-furnace-400">Hydraulic Synchronization:</strong> Proportional flow valves maintain sub-millimeter level synchronization across all beam cylinders.</li>
                                </ul>
                            </div>
                        </div>

                        <p>
                            Because billets never drag along the hearth, surface scratch defects are totally eradicated—a decisive requirement for SBQ (Special Bar Quality) alloy steels and exposed automotive sheet stock.
                        </p>
                    </section>

                    {/* Section 3 - Comparison & Skid Marks */}
                    <section className="space-y-5">
                        <h2 className="text-2xl font-bold text-white flex items-center gap-2 font-heading">
                            <BarChart3 className="text-furnace-500" size={22} />
                            3. Eliminating Skid Marks: Pusher vs. Walking Beam Thermodynamics
                        </h2>
                        <p>
                            In a legacy pusher reheat furnace of a steel mill, water-cooled tubular skid pipes carry the full sliding weight of the charge. These massive cold water pipes create severe localized thermal shadows known as "skid marks".
                        </p>
                        <p>
                            In pusher operations, the temperature differential between the bulk steel and the skid mark zone can reach 60°C to 100°C. To ensure that these cold shadows still deform adequately in the roughing mill, furnace operators are forced to overheat the entire charge by 40°C to 70°C. This deliberate overheating wastes 8% to 15% in extra fuel and dramatically accelerates oxidation scale formation.
                        </p>
                        <p>
                            In a walking beam steel mill configuration, stock rests on localized refractory saddles. Contact points shift during transport, eliminating persistent shadows and reducing delta temperature ΔT across the billet to less than 15°C. The mill can safely lower discharge target temperatures from 1,220°C down to 1,160°C, delivering instant fuel savings of 6% to 10%.
                        </p>
                    </section>

                    {/* Section 4 - Fiber Roof */}
                    <section className="space-y-5">
                        <h2 className="text-2xl font-bold text-white flex items-center gap-2 font-heading">
                            <Flame className="text-furnace-500" size={22} />
                            4. Heat Loss Mitigation: CISA T80 Full-Fiber Modular Roof Upgrade
                        </h2>
                        <p>
                            Traditional refractory brick or monolithic castable roofs possess enormous thermal mass. During rolling mill delays and weekend shutdowns, heavy refractories slowly radiate stored heat outward through the furnace casing, wasting valuable gigajoules.
                        </p>
                        <p>
                            Retrofitting with a modular ceramic full-fiber roof certified under CISA T80 standards achieves transformative thermodynamic benefits:
                        </p>
                        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-1">
                            <div className="bg-slate-900 p-4 rounded-xl border border-slate-800 text-center">
                                <div className="text-furnace-400 font-bold text-2xl mb-1">&gt; 40%</div>
                                <div className="text-xs text-slate-300 font-medium">Ceiling Heat Flux Reduction</div>
                                <div className="text-[11px] text-slate-500 mt-1">Eliminates structural hot spots</div>
                            </div>
                            <div className="bg-slate-900 p-4 rounded-xl border border-slate-800 text-center">
                                <div className="text-furnace-400 font-bold text-2xl mb-1">&lt; 2 Hours</div>
                                <div className="text-xs text-slate-300 font-medium">Cold Startup Window</div>
                                <div className="text-[11px] text-slate-500 mt-1">vs 24-48 hrs for castable crowns</div>
                            </div>
                            <div className="bg-slate-900 p-4 rounded-xl border border-slate-800 text-center">
                                <div className="text-furnace-400 font-bold text-2xl mb-1">90% Lighter</div>
                                <div className="text-xs text-slate-300 font-medium">Structural Weight Reduction</div>
                                <div className="text-[11px] text-slate-500 mt-1">Minimizes steel frame stress</div>
                            </div>
                        </div>
                        <p>
                            Complementing the modular fiber ceiling, installing high-efficiency metallic radiation recuperators recycles flue gas exhaust energy back into preheated combustion air (typically 420°C to 550°C). Re-injecting sensible flue heat directly into the burner flame elevates adiabatic combustion temperatures and lowers specific fuel consumption by an additional 8% to 14%.
                        </p>
                    </section>

                    {/* Section 5 - Turnkey Revamping Solutions */}
                    <section className="space-y-5 bg-slate-900/60 border border-slate-800 p-7 rounded-2xl">
                        <h2 className="text-2xl font-bold text-white flex items-center gap-2 font-heading">
                            <Wrench className="text-furnace-500" size={22} />
                            5. Turnkey Furnace Revamping Solutions: Pusher to Walking Beam
                        </h2>
                        <p>
                            Unlike traditional walking beam furnace manufacturers that demand greenfield capital expenditures exceeding $3M to $6M and months of plant downtime, our specialized furnace revamping solutions focus on brownfield revitalization:
                        </p>
                        <ul className="space-y-2 text-sm text-slate-300">
                            <li className="flex items-start gap-2">
                                <CheckCircle2 className="text-furnace-400 shrink-0 mt-0.5" size={16} />
                                <span><strong>Foundation Retention:</strong> We preserve the existing reinforced concrete civil foundations and exterior steel shells, avoiding major civil demolition costs.</span>
                            </li>
                            <li className="flex items-start gap-2">
                                <CheckCircle2 className="text-furnace-400 shrink-0 mt-0.5" size={16} />
                                <span><strong>Offsite Modular Fabrication:</strong> Mechanical walking beam sub-assemblies, pre-piped valve racks, and fiber roof modules are pre-assembled and shop-tested prior to mill arrival.</span>
                            </li>
                            <li className="flex items-start gap-2">
                                <CheckCircle2 className="text-furnace-400 shrink-0 mt-0.5" size={16} />
                                <span><strong>15–25 Day Shutdown Execution:</strong> On-site installation is scheduled to coincide with planned annual mill maintenance overhauls, eliminating unscheduled production losses.</span>
                            </li>
                            <li className="flex items-start gap-2">
                                <CheckCircle2 className="text-furnace-400 shrink-0 mt-0.5" size={16} />
                                <span><strong>Zero CAPEX Commercial Structuring:</strong> Under our furnace revamping solutions zero capex model, the technology provider finances 100% of the project capital, repaid exclusively out of verified monthly energy savings.</span>
                            </li>
                        </ul>
                        <p>
                            Our engineering scope encompasses laser-aligned beam carriage tracks, high-pressure hydraulic power unit (HPU) testing, and automated combustion safety controls compliant with international thermal standards. By modernizing existing furnace assets rather than purchasing new equipment, mills achieve an immediate return on investment while maintaining continuous compliance with tightened carbon emission thresholds.
                        </p>

                        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-3">
                            <div className="bg-slate-950/80 p-3.5 rounded-lg border border-slate-800">
                                <div className="text-furnace-400 font-bold text-xl">12% – 20%</div>
                                <div className="text-xs text-slate-300 mt-0.5">Typical Fuel Gas Reduction</div>
                            </div>
                            <div className="bg-slate-950/80 p-3.5 rounded-lg border border-slate-800">
                                <div className="text-furnace-400 font-bold text-xl">&lt; 25 Days</div>
                                <div className="text-xs text-slate-300 mt-0.5">Fast-Track Turnkey Installation</div>
                            </div>
                            <div className="bg-slate-950/80 p-3.5 rounded-lg border border-slate-800">
                                <div className="text-furnace-400 font-bold text-xl">$0 CAPEX</div>
                                <div className="text-xs text-slate-300 mt-0.5">Energy Steward Contract Financing</div>
                            </div>
                        </div>
                    </section>

                    {/* Dual High-Conversion Action Box */}
                    <div className="glass-panel border-furnace-500/30 rounded-2xl p-6 sm:p-8 bg-gradient-to-r from-slate-900 via-slate-900 to-slate-950 my-12 space-y-6">
                        <div>
                            <span className="text-xs uppercase font-bold tracking-wider text-furnace-400 block mb-1">
                                Engineering Verification & Feasibility Study
                            </span>
                            <h3 className="text-xl font-bold text-white">Benchmark Your Walking Beam Energy Performance</h3>
                            <p className="text-sm text-slate-400 mt-1">
                                Whether calculating your furnace heat balance, auditing specific fuel consumption, or planning a full pusher-to-walking-beam revamping, our metallurgical engineering team provides complete thermodynamic modeling.
                            </p>
                        </div>
                        <div className="flex flex-col sm:flex-row gap-4">
                            <Link
                                to="/calculators/reheating-furnace-heat-balance"
                                className="inline-flex items-center justify-center gap-2 py-3 px-5 bg-slate-800 hover:bg-slate-700 text-white rounded-lg transition-colors font-semibold text-sm border border-slate-700"
                            >
                                <Calculator size={16} className="text-furnace-400" />
                                Heat Balance Calculator
                            </Link>
                            <Link
                                to="/about#assessment"
                                className="inline-flex items-center justify-center gap-2 py-3 px-6 bg-furnace-500 hover:bg-furnace-600 text-white rounded-lg transition-colors font-bold text-sm uppercase tracking-wider shadow-lg shadow-furnace-500/20"
                            >
                                Request Revamp Feasibility Study
                                <ArrowRight size={16} />
                            </Link>
                        </div>
                    </div>

                    {/* FAQ Schema display */}
                    <section className="border-t border-slate-800 pt-10">
                        <h3 className="text-xl font-bold text-white mb-6 flex items-center gap-2">
                            <HelpCircle className="text-furnace-500" size={20} />
                            Frequently Asked Reheating Furnace Questions
                        </h3>
                        <div className="space-y-5">
                            <div className="bg-slate-900/50 p-5 rounded-xl border border-slate-800/80">
                                <h4 className="font-semibold text-white mb-2">Q: What is a reheating furnace and its primary working principle?</h4>
                                <p className="text-sm text-slate-400">A: A reheating furnace of a rolling mill is an industrial thermal reactor that heats solid steel stock (billets, blooms, or slabs) to plastically deformable temperatures (typically 1,150°C to 1,250°C). Its working principle involves transferring thermal energy generated by air-gas burners to steel charges via radiation and forced convection while maintaining tight reheat furnace temperature control.</p>
                            </div>
                            <div className="bg-slate-900/50 p-5 rounded-xl border border-slate-800/80">
                                <h4 className="font-semibold text-white mb-2">Q: What are the primary types of reheating furnace in steel mills?</h4>
                                <p className="text-sm text-slate-400">A: The primary types of reheating furnace in steel rolling mills include pusher-type furnaces, walking beam type reheating furnaces, walking hearth furnaces, and rotary hearth furnaces. Among these, the walking beam furnace is the premier choice for modern rolling mill efficiency and slab surface quality.</p>
                            </div>
                            <div className="bg-slate-900/50 p-5 rounded-xl border border-slate-800/80">
                                <h4 className="font-semibold text-white mb-2">Q: How does the walking beam furnace mechanism eliminate skid marks?</h4>
                                <p className="text-sm text-slate-400">A: The walking beam furnace mechanism uses stationary and moving refractory-insulated beams operated by eccentric or hydraulic lift-and-shift drives. Because the moving beams periodically lift stock off the stationary hearth rather than sliding it across water-cooled rails, physical contact with cold skid pipes is eliminated, removing thermal shadow skid marks.</p>
                            </div>
                            <div className="bg-slate-900/50 p-5 rounded-xl border border-slate-800/80">
                                <h4 className="font-semibold text-white mb-2">Q: Can an existing pusher furnace be revamped into a walking beam furnace?</h4>
                                <p className="text-sm text-slate-400">A: Yes. Pusher-to-walking-beam revamping is a proven engineering solution. By retaining the existing civil foundation and outer shell while retrofitting the mechanical walking beam mechanism, modern combustion staging, and fiber roofs, mills achieve 12-20% fuel savings within a standard 15-25 day maintenance window.</p>
                            </div>
                            <div className="bg-slate-900/50 p-5 rounded-xl border border-slate-800/80">
                                <h4 className="font-semibold text-white mb-2">Q: What are furnace revamping solutions under the zero CAPEX model?</h4>
                                <p className="text-sm text-slate-400">A: Furnace revamping solutions under the zero CAPEX model allow steel mills to execute turnkey walking beam upgrades with $0 upfront investment. The engineering provider finances all hardware, materials, and labor, recovering capital solely through a verified share of monthly fuel and scale savings.</p>
                            </div>
                        </div>
                    </section>

                    {/* Related Engineering Deep Dives & Topic Cluster */}
                    <section className="border-t border-slate-800 pt-10 my-10">
                        <h3 className="text-xl font-bold text-white mb-6 flex items-center gap-2">
                            <BookOpen className="text-furnace-500" size={20} />
                            Related Rolling Mill & Thermal Engineering Guides
                        </h3>
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                            <Link
                                to="/blog/hot-rolling-mill-energy-efficiency"
                                className="p-5 bg-slate-900/60 hover:bg-slate-900 border border-slate-800 hover:border-furnace-500/50 rounded-xl transition-all group block"
                            >
                                <span className="text-xs uppercase font-bold tracking-wider text-furnace-400 block mb-1">
                                    Mill-Wide Energy Guide
                                </span>
                                <h4 className="text-sm font-bold text-white group-hover:text-furnace-400 transition-colors">
                                    Hot Rolling Mill Energy Efficiency →
                                </h4>
                                <p className="text-xs text-slate-400 mt-2 line-clamp-3">
                                    Comprehensive guide covering scale loss reduction, mill pacing synchronization, and finishing stand power optimization.
                                </p>
                            </Link>
                            <Link
                                to="/blog/energy-efficiency-for-indonesian-steel-rolling-mills-reheating-furnace-audit-and-roi"
                                className="p-5 bg-slate-900/60 hover:bg-slate-900 border border-slate-800 hover:border-furnace-500/50 rounded-xl transition-all group block"
                            >
                                <span className="text-xs uppercase font-bold tracking-wider text-furnace-400 block mb-1">
                                    On-Site Field Audit
                                </span>
                                <h4 className="text-sm font-bold text-white group-hover:text-furnace-400 transition-colors">
                                    Reheating Furnace Audit in Indonesia →
                                </h4>
                                <p className="text-xs text-slate-400 mt-2 line-clamp-3">
                                    Field audit methodologies, thermal loss mapping, and zero-CAPEX retrofitting for Cilegon and Surabaya rolling lines.
                                </p>
                            </Link>
                            <Link
                                to="/blog/reheating-furnace-fuel-saving-guide"
                                className="p-5 bg-slate-900/60 hover:bg-slate-900 border border-slate-800 hover:border-furnace-500/50 rounded-xl transition-all group block"
                            >
                                <span className="text-xs uppercase font-bold tracking-wider text-furnace-400 block mb-1">
                                    Fuel Saving Guide
                                </span>
                                <h4 className="text-sm font-bold text-white group-hover:text-furnace-400 transition-colors">
                                    Reheating Furnace Fuel Saving Guide →
                                </h4>
                                <p className="text-xs text-slate-400 mt-2 line-clamp-3">
                                    Tactical interventions to cut gas consumption by 15-20% through oxygen trim, recuperators, and fiber linings.
                                </p>
                            </Link>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    );
};

export default WalkingBeamGuide;
